version: '3.4'

services:
  cqrsMSSQL:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cqrsMSSQL
    restart: always
    environment:
      - ACCEPT_EULA=N
      - MSSQL_SA_PASSWORD=P@ssw0rd02
      - MSSQL_PID=Express
    ports:
      - 1433:1433

  cqrsMongo:
    container_name: cqrsMongo
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb_data_container:/data/db

  cqrsZookeeper:
    container_name: cqrsZookeeper
    image: bitnami/zookeeper
    restart: always
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  cqrsKafka:
    container_name: cqrsKafka
    image: bitnami/kafka
    ports:
      - 9092:9092
    restart: always
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=cqrsZookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - cqrsZookeeper

volumes:
  mongodb_data_container:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  default:
    name: my_cqrs_network